### ISSUE TITLE
System lockups with the new 1.1 release

### ISSUE THREAD

**Issue by razneck** [joel16/PSV-VSH-Menu#3]
Plugin is loaded as *ALL and the initial release worked like intended.
With the new release I have noticeable stutter/slowdown in the main shell which is strange in itself.
And constant random total system lockups while browsing files in vitashell and doing simple file operations.
I also have a SD2Vita adapter with the SD loaded as main memory, maybe it's relevant.

**Comment by joel16** [comment]
Weird, I don't use *ALL due to the problem of having it conflict with other plugins however I did just try it and didn't notice any slow down in the main shell or anything. Although, I did notice it fails to load on some games, and causes crashes if you try changing the options in other games. It's weird because, when I run it under a  specific titles it works fine. I guess I'll have to do some experimenting.

Do you mind running it on a specific titleID and see if it works any better? (You'll have to comment *ALL line and reboot to save changes)

**Comment by joel16** [comment]
Closing this due to lack of response.
