### ISSUE TITLE
VSH menu doesn't show up on a few games

### ISSUE THREAD

**Issue by masterrite** [joel16/PSV-VSH-Menu#9]
Hi there,

I tested the 2.0 version, but the menu doesn't show up on PCSH00297 YS VIII. It works with other games, however. I think it might be due to its using a mass amount of memory (but then oclockvita and batterypercent both worked fine with it before) or because a combo for pressing L and R button together exist as a control in-game.

Can you look into it?

Also, is there a way to keep battery information on-screen even after turning off the vsh menu?

Thanks!

**Comment by masterrite** [comment]
oh I'm on 3.60 enso by the way

**Comment by joel16** [comment]
Can you open ur0:/data/vsh/titles/ and see if the PCSH00297.cfg exists? If it does exist is it empty?

**Comment by masterrite** [comment]
nope. it's not there. should I create one myself?

**Comment by joel16** [comment]
No, the app should generate one by itself. It seems like there may be some sort of conflict. I don't have too many games so it's hard for me to test. I'll try looking into it later. Also about the battery info, I'll add one more option in the next release to keep the battery display on even after you close the VSH Menu. I assumed people would be bothered if it always stayed on top, but some people actually do want it, so that should be available in next bug fix update (should be soon!)

**Comment by masterrite** [comment]
Thanks! [Here's ](https://mega.nz/#!hDQliZbQ!1fKWRgEhmt-0elUyBByy1Lxw9yv89NbRpGLpJQB6NCo)the game dump from my own game cartridge (Traditional Chinese version) if you ever need it. I believe it's nonpdrm version.
 
I really like the batterypercent plugin (I believe it's also by you?), and having it onscreen in my game acts like a time control.
 
Thanks for the help!

**Comment by joel16** [comment]
Fixed with https://github.com/joel16/PSV-VSH-Menu/commit/943fd21b3303f1d9038dadca93c3b2942b8c3418
